name: SanwoExample
options:
  bundleIdPrefix: com.sanwohq.example
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "16.0"

packages:
  Sanwo:
    url: https://github.com/Sanwohq/ios.git
    from: "0.1.2"

targets:
  SanwoExample:
    type: application
    platform: iOS
    sources:
      - SanwoExample
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_VERSION: "5.9"
    dependencies:
      - package: Sanwo
        product: Sanwo
      - package: Sanwo
        product: SanwoPaystack
      - package: Sanwo
        product: SanwoFlutterwave
      - package: Sanwo
        product: SanwoRazorpay
      - package: Sanwo
        product: SanwoMonnify
      - package: Sanwo
        product: SanwoInterswitch
